### ISSUE TITLE
Embedded CSS Analyzer breaking if the HTML files have UTF8 encoding with BOM

### ISSUE THREAD

**Issue by VamseeInala** [racodond/sonar-css-plugin#53] opened 2017-07-27 04:45 UTC
Hi,

The embedded CSS analyser is breaking if any of the source files with having UTF8 with BOM encoding. 

This issue can be reproduced by creating any HTML file with UTF8-BOM encoding and running the analyser on it.

The stack trace is something like below: 
<addr>
2017-07-26T12:02:02.2237054Z ##[error]java.lang.IllegalArgumentException: 26 is not a valid line offset for pointer. File [<<removed file names>>.html] has 24 character(s) at line 1
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:215)
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:206)
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:237)
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.plugins.css.IssueSaver.newLocation(IssueSaver.java:128)
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.plugins.css.IssueSaver.savePreciseIssue(IssueSaver.java:61)
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.plugins.css.IssueSaver.saveIssue(IssueSaver.java:51)
2017-07-26T12:02:02.2237054Z ##[error]at java.util.ArrayList.forEach(ArrayList.java:1249)
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.plugins.css.AbstractLanguageAnalyzerSensor.saveSingleFileIssues(AbstractLanguageAnalyzerSensor.java:170)
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.plugins.css.AbstractLanguageAnalyzerSensor.execute(AbstractLanguageAnalyzerSensor.java:114)
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247)
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242)
2017-07-26T12:02:02.2237054Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:240)
2017-07-26T12:02:02.2247050Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232)
2017-07-26T12:02:02.2247050Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
2017-07-26T12:02:02.2247050Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
2017-07-26T12:02:02.2247050Z ##[error]at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
2017-07-26T12:02:02.2247050Z ##[error]at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
2017-07-26T12:02:02.2247050Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
2017-07-26T12:02:02.2247050Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
2017-07-26T12:02:02.2247050Z ##[error]at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
2017-07-26T12:02:02.2247050Z ##[error]at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118)
2017-07-26T12:02:02.2247050Z ##[error]at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
2017-07-26T12:02:02.2247050Z ##[error]at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2017-07-26T12:02:02.2247050Z ##[error]at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2017-07-26T12:02:02.2247050Z ##[error]at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2017-07-26T12:02:02.2247050Z ##[error]at java.lang.reflect.Method.invoke(Method.java:498)
2017-07-26T12:02:02.2247050Z ##[error]at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
2017-07-26T12:02:02.2247050Z ##[error]at com.sun.proxy.$Proxy0.execute(Unknown Source)
2017-07-26T12:02:02.2247050Z ##[error]at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
2017-07-26T12:02:02.2247050Z ##[error]at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
2017-07-26T12:02:02.2247050Z ##[error]at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
2017-07-26T12:02:02.2247050Z ##[error]at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
2017-07-26T12:02:02.2247050Z ##[error]at org.sonarsource.scanner.cli.Main.main(Main.java:61)
2017-07-26T12:02:02.2247050Z ##[error]ERROR:
</addr>
Thanks
Vamsee

**Comment by racodond** [comment] 2017-08-02 12:40
Hi @VamseeInala,

I cannot reproduce the issue. It must be a corner case. Thus, to investigate, I need you to provide me with a sample HTML file with a BOM and a backup of your CSS quality profile.

Thank you

David

**Comment by SuruchiMohan** [comment] 2017-08-17 11:42
Here is the sample html and scss file:
[Test.zip](https://github.com/racodond/sonar-css-plugin/files/1231112/Test.zip)
Please try on this.

**Comment by racodond** [comment] 2017-08-21 08:42
Hi @SuruchiMohan,

In your sample project, the HTML file does not contain any CSS code...
I'm closing the issue. Feel free to add a comment with a proper example if you can reproduce the issue.

Regards,

David Racodon

**Closed as completed by racodond** 2017-08-21 08:42 UTC
Labels: question

**Comment by SuruchiMohan** [comment] 2017-08-21 09:26
Hi @racodond ,

In my project we don't have an embedded css, instead have external css files. In the sample attached, I have provided both css and html.
Also, the issue is not restricted to html and css. The Analyzer is unable to read other files types also. Some examples are:
**JSON**
2017-08-18T16:06:22.7916366Z ##[error]ERROR: Unable to parse file: D:/a/1/s/App/UI/dist/app/js/services/data.json
2017-08-18T16:06:22.7916366Z ##[error]ERROR: Parse error at line 1 column 1:
2017-08-18T16:06:22.7916366Z ##[error]
2017-08-18T16:06:22.7916366Z ##[error]1: ∩╗┐{
2017-08-18T16:06:22.7916366Z ##[error]^
2017-08-18T16:06:22.7916366Z ##[error]2:   "applications": [

**JS**
2017-08-18T16:06:22.7946377Z ##[error]ERROR: Unable to parse file: D:/a/1/s/App/UI/Scripts/provider.js
2017-08-18T16:06:22.7946377Z ##[error]ERROR: Parse error at line 1 column 2:
2017-08-18T16:06:22.7946377Z ##[error]
2017-08-18T16:06:22.7946377Z ##[error]1: ∩╗┐
2017-08-18T16:06:22.7946377Z ##[error]^
2017-08-18T16:06:22.7946377Z ##[error]2: (function () {

From what I guess, when we save a file in UTF8 with BOM encoding format, there are some special characters appended in the start of the file, which the analyzer is unable t0 parse.

**Comment by racodond** [comment] 2017-08-21 09:30
OK. Thus don't hijack this thread as your issue is not related to "Embedded CSS Analyzer breaking if the HTML files have UTF8 encoding with BOM" but to JSON or JavaScript. Your issue is likely related to a misconfiguration of your analysis. See sonar.sourceEncoding at https://docs.sonarqube.org/display/SONAR/Analysis+Parameters.
