### ISSUE TITLE
less:semicolon-declaration on selector groupings

### ISSUE THREAD

**Issue by MundakaZgz** [racodond/sonar-css-plugin#65] opened 2017-10-06 12:03 UTC
Hi there,

I have come across with this issue which I think is a bug.
When I group selectors in CSS using comma I get this message:

![sonar1](https://user-images.githubusercontent.com/1915825/31277007-09846610-aa9f-11e7-9f8d-d0a9b3386beb.PNG)

The code where I get this error is:
`
accordion-panel:not(:last-child),
treatment-plan-summary > .accordion-container:not(:last-child) {
  margin-bottom: @size-xs / 2;
}
`

Could you help me?

Thanks,

Jose

**Comment by racodond** [comment] 2017-10-06 12:22
Hi @MundakaZgz,

I can't reproduce the issue. Are you running the latest version of the plugin: https://github.com/racodond/sonar-css-plugin/releases/tag/4.10 ?

Thank you

David

**Comment by MundakaZgz** [comment] 2017-10-13 07:34
The version I am using is 3.1. I see that the latest version is 4.1. I'll try to install it manually as the Update Center doesn't give me the option to udpdate it.

**Comment by racodond** [comment] 2017-10-19 13:52
I'm closing this issue. Feel free to reopen it if you manage to reproduce your issue with version 4.10.

**Closed as completed by racodond** 2017-10-19 13:52 UTC
Labels: question
